diccionario/diccionario/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('sobre_el_diccionario/', views.sobre, name='sobre'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diccionario/search/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
    path('', views.index, name='searchindex'),
    path('results/', views.search, name='search'),
    path('results_letter/', views.search_letter, name='search_letter'),
    path('<int:word_id>/', views.detail, name='detail'),
    path('new/', views.new_word, name='post_new'),
    path('approve/', views.aprobar, name='post_aprobar')
]

diccionario/search/models.py
from django.db import models

# Create your models here.

class Example(models.Model):
    example_text = models.CharField(max_length=200)

    def __str__(self):
        return self.example_text


class Origin(models.Model):
    origin_text = models.CharField(max_length=30)

    def __str__(self):
        return self.origin_text

class Word(models.Model):
    '''
    A word has a text and it can have multiple meanings and examples.
    Later it may be implemented a related words section.
    '''
    word_text = models.CharField(max_length=30)
    word_examples = models.ForeignKey(Example, on_delete=models.CASCADE, default=None)
    word_origin = models.ForeignKey(Origin, on_delete=models.CASCADE, default=None)
    pub_date = models.DateTimeField('date published')
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.word_text


class Meaning(models.Model):
    meaning_text = models.CharField(max_length=200)
    word = models.ForeignKey(Word, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.meaning_text

diccionario/search/forms.py
from django import forms
from .models import Word

class NewWord(forms.Form):
	word = forms.CharField(required=True,max_length=30, label="Ingresar palabra")
	meaning = forms.CharField(required=True,max_length=200, label="Ingresar significado")
	example = forms.CharField(max_length=200, label="Ingresar ejemplo de uso")
	origin = forms.CharField(max_length=30, label="Ingresar origen de la palabra")

class ApproveWord(forms.Form):	
	word_id = forms.IntegerField(required=False)

diccionario/diccionario/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect, get_object_or_404


def index(request):
	return redirect('/search')

def sobre(request):
    return render(request, 'sobre_el_diccionario.html')

diccionario/search/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import Http404
from .models import Word, Meaning, Example, Origin
from django.template import loader
from django.utils import timezone
from .forms import NewWord, ApproveWord
from random import sample
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def index(request):
    context = {}
    # latest_word_list = Word.objects.order_by('-pub_date')[:6]
    latest_word_list = Word.objects.filter(approved=True).order_by('-pub_date')[:6]
    word_list = []
    print(latest_word_list)
    for word in latest_word_list:
        meaning = Meaning.objects.filter(word__pk=word.pk).first()
        word_list.append((word,meaning))
    context['latest_word_list'] = word_list
    return render(request, 'search/index.html', context)


def detail(request, word_id):
    context = {}
    word = get_object_or_404(Word, pk=word_id)
    context['word'] = word
    # count = Wordself.objects.all().count()
    # rand_ids = sample(range(1, count+1), 4 if count >= 4 else count)
    # if  word.id in rand_ids:
        # rand_ids.remove(word.id)
    context['random_words'] = Word.objects.all().exclude(pk = word.pk).order_by('?')[:4]
    context['meanings'] = Meaning.objects.filter(word=word)
    return render(request, 'search/detail.html', context)


def aprobar(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = ApproveWord(request.POST)
            if form.is_valid():
                wid = request.POST['word_id']
                word = Word.objects.get(pk=wid)
                if request.POST['button'] == 'aprobar':
                    word.approved = True
                    word.save()
                elif request.POST['button'] == 'eliminar':
                    word.delete()

                else:
                    # Esto esta medio cualquiera pero es la forma rapida que se me ocurrio.
                    # Basicamente cada boton eliminar del form aprobar tiene seguido de un /
                    # el id del meaning a eliminar. Si ya se, pero funciona xD.

                    meaning_id = request.POST['button'].split('/')[1]
                    meaning = Meaning.objects.filter(pk=meaning_id)
                    meaning.delete()
        else:
            form = ApproveWord()

        words = Word.objects.filter(approved=False)
        pairs = []
        for w in words:
            meanings = [m for m in Meaning.objects.filter(word=w)]
            pairs.append((w, meanings))

        context = {'words' : pairs, 'form': form}
        return render(request, 'search/aprobar.html', context)
    else:
        redirect('/search')


def new_word(request):
    latest_word_list = Word.objects.order_by('-pub_date')[:5]
    context = {'latest_word_list': latest_word_list}

    if request.method == "POST":
        print(request.POST)
        form = NewWord(request.POST)
        if form.is_valid():
            word_text = request.POST['word']
            word = Word.objects.filter(word_text=word_text)
            if word:
                redirect('/search/' + word[0].id)

            if request.POST['example']:
                example = Example(example_text=request.POST['example'])
                example.save()
            if request.POST['origin']:
                origin = Origin(origin_text=request.POST['origin'])
                origin.save()

            word = Word(word_text=request.POST['word'], pub_date=timezone.now(), word_examples=example, word_origin=origin)
            word.save()

            all_meanings = request.POST.getlist('meaning')
            for m in all_meanings:
                meaning = Meaning(meaning_text=m, word=word)
                meaning.save()
            redirect('/search')
    else:
        form = NewWord()
    return render(request, 'search/new_word.html', {'form': form}, context)


def search(request):
  if request.GET:
    searcher = request.GET["searcher"]
    number = len(Word.objects.all())
    words = Word.objects.filter(word_text__contains=searcher, approved=True)
    # Caso donde no haya palabras que coincidan con la busqueda
    list_word = []
    for word in words:
        meaning = Meaning.objects.filter(word=word).first()
        list_word.append((word,meaning))
    if len(words) == 0:
        context = {'busqueda' : searcher}
        return render(request, 'search/no_results.html', context)
    page = request.GET.get('page', 1)
    paginator = Paginator(words, len(words))
    try:
      catalogo = paginator.page(page)
    except PageNotAnInteger:
      catalogo = paginator.page(1)
    except EmptyPage:
      catalogo = paginator.page(paginator.num_pages)
    pagscount = paginator.count
    number = len(Word.objects.all())
    context = {'busqueda' : list_word, 'pagscount' : pagscount, 'number' : number}
  return render(request, "search/results.html", context)

def search_letter(request):
  if request.GET:
    searcher = request.GET["searcher"]
    searcher = searcher.lower()
    number = len(Word.objects.all())
    words = Word.objects.filter(word_text__contains=searcher)
    wordlist = []
    for word in words:
        if str(word).startswith(searcher):
            wordlist.append(word)
    list_word = []
    for word in wordlist:
        meaning = Meaning.objects.filter(word=word).first()
        list_word.append((word,meaning))
    # Caso donde no haya palabras con esa letra
    if len(wordlist) == 0:
        return render(request, 'search/no_results.html')
    page = request.GET.get('page', 1)
    paginator = Paginator(wordlist, len(wordlist))
    try:
      catalogo = paginator.page(page)
    except PageNotAnInteger:
      catalogo = paginator.page(1)
    except EmptyPage:
      catalogo = paginator.page(paginator.num_pages)
    pagscount = paginator.count
    number = len(Word.objects.all())
    context = {'busqueda' : list_word, 'pagscount' : pagscount, 'number' : number}
  return render(request, "search/results.html", context)

diccionario/search/templates/search/aprobar.html
{% extends "base.html" %} {% block content %}


<div class="grey lighten-2" style=" padding-left:20px; padding-right:20px; padding-top:30px; padding-bottom:30px;">
  <div class="row">
    <div class="col l2 s12" style="padding:0px;">

      <div class="white z-depth-5 rcorners3">
        <form id="searchform" action={% url 'search:search' %} method="GET" style="margin-bottom:40px;">
          <div class="row" style="margin-bottom:0px !important;">
            <div class="col s12">
              <h5 class="center-align"><br><b>Buscar Definiciones:</b></h5>
              <input class="searchfield" id="searcher" name="searcher" type="text" placeholder="Ingresar palabra">
            </div>
          </div>
          <div class="center-align">
            <button type="submit" class="btn waves-effect grey"><i class="material-icons right">search</i>Buscar</button>
          </div>
        </form>
        <div class="center-align grey darken-3">
          <a class="btn red rcorners3" href="/search/new/" style="margin-top:20px; margin-bottom:20px;"><b>Agregar Palabra</b></a>
        </div>
        {% if request.user.is_superuser %}
        <div class="center-align grey darken-3">
          <a class="btn green rcorners3" href="/search/approve/" style="margin-top:20px; margin-bottom:20px;"><b>Aprobar Palabras</b></a>
        </div>
        {% endif %}
      </div>

      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; padding:20px; min-height:50px; line-height:50px;">
        <img src="/media/Sofiacart.png" style="width:100%;">
      </div>
      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; min-height:50px; line-height:50px;">
        <img src="/media/foro-lenguas-mapa.jpg" class="materialboxed" style="width:100%;">
      </div>


    </div>

    <div class="col l10 s12">

      <div class="white" style="padding:20px;">


        {% if not words %}
        <div class="container">
          <h5 class="blue white-text center-align" style="padding:30px;">No hay palabras para aprobar</h5>
        </div>
        {% else %}

        <h5 class="left-align"><b>Acepta las palabras nuevas!</b></h5> {% endif %}
        {% for word, meanings in words %}
        <div class="grey lighten-3" style="padding:20px; margin-bottom:20px;">


        <p>
          <form action="/search/approve/" method="POST">
            {%csrf_token%} <font size="5"><b>{{word.word_text}}:</b>
            {% for meaning in meanings %}
            <p> {{forloop.counter}}- {{ meaning.meaning_text }}</p> <button type="submit" class="btn waves-effect red" name="button" value="eliminar_significado/{{meaning.id}}"><i class="material-icons right">delete</i>Eliminar</button>
            {% endfor %}
            </font> <br> <font size="3"> <b> Ejemplo:</b> {{word.word_examples}}</font> <br> <b>Origen:</b> {{word.word_origin}}<br>
            <br>
            <input type="hidden" name="word_id" value="{{word.id}}">
            <button type="submit" class="btn waves-effect green" name="button" value="aprobar"><i class="material-icons right">check</i>Aprobar</button>
            <button type="submit" class="btn waves-effect red" name="button" value="eliminar"><i class="material-icons right">delete</i>Eliminar</button>
          </form>
        </p>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</div>
{% endblock %}

diccionario/search/templates/search/detail.html
{% extends "base.html" %} {% block content %}

<div class="grey lighten-2" style=" padding-left:20px; padding-right:20px; padding-top:30px; padding-bottom:30px;">
  <div class="row">
    <div class="col l2 s12" style="padding:0px;">

      <div class="white z-depth-5 rcorners3">
        <form id="searchform" action={% url 'search:search' %} method="GET" style="margin-bottom:40px;">
          <div class="row" style="margin-bottom:0px !important;">
            <div class="col s12">
              <h5 class="center-align"><br><b>Buscar Definiciones:</b></h5>
              <input class="searchfield" id="searcher" name="searcher" type="text" placeholder="Ingresar palabra">
            </div>
          </div>
          <div class="center-align">
            <button type="submit" class="btn waves-effect grey"><i class="material-icons right">search</i>Buscar</button>
          </div>
        </form>
        <div class="center-align grey darken-3">
          <a class="btn red rcorners3" href="/search/new/" style="margin-top:20px; margin-bottom:20px;"><b>Agregar Palabra</b></a>
        </div>
        {% if request.user.is_superuser %}
        <div class="center-align grey darken-3">
          <a class="btn green rcorners3" href="/search/approve/" style="margin-top:20px; margin-bottom:20px;"><b>Aprobar Palabras</b></a>
        </div>
        {% endif %}
      </div>

      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; padding:20px; min-height:50px; line-height:50px;">
        <img src="/media/Sofiacart.png" style="width:100%;">
      </div>
      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; min-height:50px; line-height:50px;">
        <img src="/media/foro-lenguas-mapa.jpg" class="materialboxed" style="width:100%;">
      </div>


    </div>
    <div class="col l10 s12 lighten-4" style="padding-left:25px;">
      <div class="hide-on-med-and-up" style="height:10px; margin-top:30px;">
      </div>
      <div class="white z-depth-5 rcorners3" style="padding:20px;">


        <h3>{{ word.word_text }}</h3>
        {% for meaning in meanings %}
        <p> {{forloop.counter}}- {{ meaning.meaning_text }}</p>
        {% endfor %}
        <p><b>Ejemplo:</b> "{{ word.word_examples }}"</p>
        <p><b>Origen:</b> {{ word.word_origin }}</p>
        <ul>
          {% for meaning in word.meaning_set.all %}
          <li>{{ add.meaning_text }}</li>
          {% endfor %}
        </ul>
        <a class="btn btn-small waves-effect waves-light blue rcorners3" onclick="goBack()" style="margin-bottom:50px;"><i class="material-icons left">arrow_back</i>Volver</a>
        <a class="btn btn-small waves-effect waves-light green rcorners3" onclick="goBack()" style="margin-bottom:50px;"><i class="material-icons right">add</i>Agregar Significado</a>

        <div class="row grey darken-3 rcorners3" style="padding:20px;">
          <h5 class="white-text left-align">Otras palabras visitadas:</h5>
          {%for i in random_words%}


          <div class="col s12 m6 l3">
            <a href="/search/{{i.id}}">
            <div class="card rcorners3 darken-1 z-depth-5">
              <div class="card-content white-text">
                <span class="black-text card-title center-align"><b>{{i}}</b></span>
                <p class="black-text">{{i.word_meaning}}</p>
              </div>
            </div>
          </a>
          </div>


          {%endfor%}
        </div>
    </div>
    </div>
  </div>
</div>



{% endblock %} {% block javascript %}

<script>
function goBack() {
          window.history.back();
      }
</script>
{% endblock %}

diccionario/search/templates/search/index.html
{% extends "base.html" %} {% block content %}

<style>
  /*the container must be positioned relative:*/

  .btn2 {
    height: auto;
    min-height: 20px;
    line-height: 20px;
    padding-top: 8px;
    padding-bottom: 8px;
  }

  .autocomplete {
    position: relative;
    display: inline-block;
  }

  input {
    border: 1px solid transparent;
    background-color: #f1f1f1;
    padding: 10px;
    font-size: 16px;
  }

  input[type=text] {
    background-color: #f1f1f1;
    width: 100%;
  }

  input[type=submit] {
    background-color: DodgerBlue;
    color: #fff;
    cursor: pointer;
  }

  .autocomplete-items {
    position: absolute;
    border: 1px solid #d4d4d4;
    border-bottom: none;
    border-top: none;
    z-index: 99;
    /*position the autocomplete items to be the same width as the container:*/
    top: 100%;
    left: 0;
    right: 0;
  }

  .autocomplete-items div {
    padding: 10px;
    cursor: pointer;
    background-color: #fff;
    border-bottom: 1px solid #d4d4d4;
  }

  /*when hovering an item:*/

  .autocomplete-items div:hover {
    background-color: #e9e9e9;
  }

  /*when navigating through the items using the arrow keys:*/

  .autocomplete-active {
    background-color: DodgerBlue !important;
    color: #ffffff;
  }
</style>


<div class="grey lighten-2" style=" padding-left:20px; padding-right:20px; padding-top:30px; padding-bottom:30px;">
  <div class="row">
    <div class="col l2 s12" style="padding:0px;">

      <div class="white z-depth-5 rcorners3">
        <form id="searchform" action={% url 'search:search' %} method="GET" style="margin-bottom:40px;">
          <div class="row" style="margin-bottom:0px !important;">
            <div class="col s12">
              <h5 class="center-align"><br><b>Buscar Definiciones:</b></h5>
              <input class="searchfield" id="searcher" name="searcher" type="text" placeholder="Ingresar palabra">
            </div>
          </div>
          <div class="center-align">
            <button type="submit" class="btn waves-effect grey"><i class="material-icons right">search</i>Buscar</button>
          </div>
        </form>
        <div class="center-align grey darken-3">
          <a class="btn red rcorners3" href="/search/new/" style="margin-top:20px; margin-bottom:20px;"><b>Agregar Palabra</b></a>
        </div>
        {% if request.user.is_superuser %}
        <div class="center-align grey darken-3">
          <a class="btn green rcorners3" href="/search/approve/" style="margin-top:20px; margin-bottom:20px;"><b>Aprobar Palabras</b></a>
        </div>
        {% endif %}
      </div>

      <!-- <div class="z-depth-5 rcorners3 white" style="margin-top:30px; min-height:300px;">
        <div style="padding:20px; line-height:300px;">
          <img src="/media/Sofiacart.png" style="width:100%;">
        </div>
      </div> -->
      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; padding:20px; min-height:50px; line-height:50px;">
        <img src="/media/Sofiacart.png" style="width:100%;">
      </div>
      <div class="container2 z-depth-5 rcorners3 center-align white" style="margin-top:20px; min-height:50px; line-height:50px;">
        <img src="/media/foro-lenguas-mapa.jpg" class="materialboxed" style="width:100%;">
      </div>
      <!-- <div class="black  z-depth-5 rcorners3" style="margin-top:30px; min-height:300px;">
        <p class="center-align white-text" style="line-height:300px;">Cartel o Publicidad</p>
      </div> -->


    </div>
    <div class="col l10 s12" style="padding-left:25px;">
      <div class="z-depth-5 rcorners3 white" style="padding:20px;">
        <h4 class="left-align">Últimas palabras añadidas:</h4> {% if latest_word_list %}
        <div class="row center-align grey lighten-3 rcorners3" style="padding: 20px; width:100%;">
          {% for word in latest_word_list %}
          <div class="col l2"><a href="{% url 'search:detail' word.0.pk %}" style="margin-top:10px;" class="white black-text btn2 btn waves-effect waves-light"><b>{{ word.0.word_text }}</b></a></div>
          {% endfor %}
        </div>
        {% else %}
        <div class="container">
          <p>No hay palabras disponibles.</p>
        </div>
        {% endif %}
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
          dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
        <hr>
        <h4 class="left-align" style="margin-top:25px;">Filtrar palabras por letra:</h4>
        <div class=" z-depth-5 center-align" style="margin-top:20px; padding:10px;">










          <!-- <form autocomplete="off" action={% url 'search:search' %} method="GET">
            <div class="autocomplete" style="width:300px;">
              <input class="searchfield" id="myInput" name="searcher" type="text" placeholder="Ingresar palabra">
            </div>
            <input type="submit">
          </form>

          <script>
          function autocomplete(inp, arr) {
            /*the autocomplete function takes two arguments,
            the text field element and an array of possible autocompleted values:*/
            var currentFocus;
            /*execute a function when someone writes in the text field:*/
            inp.addEventListener("input", function(e) {
                var a, b, i, val = this.value;
                /*close any already open lists of autocompleted values*/
                closeAllLists();
                if (!val) { return false;}
                currentFocus = -1;
                /*create a DIV element that will contain the items (values):*/
                a = document.createElement("DIV");
                a.setAttribute("id", this.id + "autocomplete-list");
                a.setAttribute("class", "autocomplete-items");
                /*append the DIV element as a child of the autocomplete container:*/
                this.parentNode.appendChild(a);
                /*for each item in the array...*/
                for (i = 0; i < arr.length; i++) {
                  /*check if the item starts with the same letters as the text field value:*/
                  if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                    /*create a DIV element for each matching element:*/
                    b = document.createElement("DIV");
                    /*make the matching letters bold:*/
                    b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                    b.innerHTML += arr[i].substr(val.length);
                    /*insert a input field that will hold the current array item's value:*/
                    b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                    /*execute a function when someone clicks on the item value (DIV element):*/
                    b.addEventListener("click", function(e) {
                        /*insert the value for the autocomplete text field:*/
                        inp.value = this.getElementsByTagName("input")[0].value;
                        /*close the list of autocompleted values,
                        (or any other open lists of autocompleted values:*/
                        closeAllLists();
                    });
                    a.appendChild(b);
                  }
                }
            });
            /*execute a function presses a key on the keyboard:*/
            inp.addEventListener("keydown", function(e) {
                var x = document.getElementById(this.id + "autocomplete-list");
                if (x) x = x.getElementsByTagName("div");
                if (e.keyCode == 40) {
                  /*If the arrow DOWN key is pressed,
                  increase the currentFocus variable:*/
                  currentFocus++;
                  /*and and make the current item more visible:*/
                  addActive(x);
                } else if (e.keyCode == 38) { //up
                  /*If the arrow UP key is pressed,
                  decrease the currentFocus variable:*/
                  currentFocus--;
                  /*and and make the current item more visible:*/
                  addActive(x);
                } else if (e.keyCode == 13) {
                  /*If the ENTER key is pressed, prevent the form from being submitted,*/
                  e.preventDefault();
                  if (currentFocus > -1) {
                    /*and simulate a click on the "active" item:*/
                    if (x) x[currentFocus].click();
                  }
                }
            });
            function addActive(x) {
              /*a function to classify an item as "active":*/
              if (!x) return false;
              /*start by removing the "active" class on all items:*/
              removeActive(x);
              if (currentFocus >= x.length) currentFocus = 0;
              if (currentFocus < 0) currentFocus = (x.length - 1);
              /*add class "autocomplete-active":*/
              x[currentFocus].classList.add("autocomplete-active");
            }
            function removeActive(x) {
              /*a function to remove the "active" class from all autocomplete items:*/
              for (var i = 0; i < x.length; i++) {
                x[i].classList.remove("autocomplete-active");
              }
            }
            function closeAllLists(elmnt) {
              /*close all autocomplete lists in the document,
              except the one passed as an argument:*/
              var x = document.getElementsByClassName("autocomplete-items");
              for (var i = 0; i < x.length; i++) {
                if (elmnt != x[i] && elmnt != inp) {
                  x[i].parentNode.removeChild(x[i]);
                }
              }
            }
            /*execute a function when someone clicks in the document:*/
            document.addEventListener("click", function (e) {
                closeAllLists(e.target);
            });
          }

          /*An array containing all the country names in the world:*/
          var countries = ["mesa", "silla", "buluca", "cafe", "decir", "cactus", "perro"];

          /*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
          autocomplete(document.getElementById("myInput"), countries);
          </script> -->





          <form id="searchform" action={% url 'search:search_letter' %} method="GET" style="display:inline-block;">
            <input type="submit" name="searcher" id="searcher" value="A" />
            <input type="submit" name="searcher" id="searcher" value="B" />
            <input type="submit" name="searcher" id="searcher" value="C" />
            <input type="submit" name="searcher" id="searcher" value="D" />
            <input type="submit" name="searcher" id="searcher" value="E" />
            <input type="submit" name="searcher" id="searcher" value="F" />
            <input type="submit" name="searcher" id="searcher" value="G" />
            <input type="submit" name="searcher" id="searcher" value="H" />
            <input type="submit" name="searcher" id="searcher" value="I" />
            <input type="submit" name="searcher" id="searcher" value="J" />
            <input type="submit" name="searcher" id="searcher" value="K" />
            <input type="submit" name="searcher" id="searcher" value="L" />
            <input type="submit" name="searcher" id="searcher" value="M" />
            <input type="submit" name="searcher" id="searcher" value="N" />
            <input type="submit" name="searcher" id="searcher" value="Ñ" />
            <input type="submit" name="searcher" id="searcher" value="O" />
            <input type="submit" name="searcher" id="searcher" value="P" />
            <input type="submit" name="searcher" id="searcher" value="Q" />
            <input type="submit" name="searcher" id="searcher" value="R" />
            <input type="submit" name="searcher" id="searcher" value="S" />
            <input type="submit" name="searcher" id="searcher" value="T" />
            <input type="submit" name="searcher" id="searcher" value="U" />
            <input type="submit" name="searcher" id="searcher" value="V" />
            <input type="submit" name="searcher" id="searcher" value="W" />
            <input type="submit" name="searcher" id="searcher" value="X" />
            <input type="submit" name="searcher" id="searcher" value="Y" />
            <input type="submit" name="searcher" id="searcher" value="Z" />
          </form>





        </div>

        <ul class="collapsible" data-collapsible="accordion" style="margin-bottom:140px;">
          {% for word in latest_word_list %}
          <li>
            <div class="collapsible-header">
              <p><i class="material-icons">adjust</i><b>{{ word.0.word_text }}:&nbsp </b> {{ word.1 }}</p>
            </div>
            <div class="collapsible-body"><a class="black-text" href="/search/{{word.0.id}}"><span><b><u>Ejemplo:</u></b>"&nbsp{{ word.0.word_examples }}" <u><br><b>Origen:</b></u>&nbsp{{ word.0.word_origin }}</span></a></div>
          </li>
          {%endfor%}
        </ul>

      </div>
    </div>
  </div>
</div>
{% endblock %} {% block javascript %}
<!-- <script type="text/javascript">
  function myFunction() {
    if ("{{palabra}}" != "None") {
      $("#searchform").submit();
    }
 }; -->
</script>
{% endblock %}